


User.create!({username: "Arnold",password: "123123", gym_id: 1,
  age: 68, weight: 249, profile_image_url: "http://daily.barbellshrugged.com/wp-content/uploads/2015/02/Screen-Shot-2015-02-05-at-10.52.48-AM.png"})
User.create!({username: "sang",password: "123123", gym_id: 1})
User.create!({username: "sang1",password: "123123", gym_id: 1})
User.create!({username: "sang2",password: "123123", gym_id: 2})
User.create!({username: "sang3",password: "123123", gym_id: 3})
User.create!({username: "sang4",password: "123123", gym_id: 4})


HomeCity.create!({name: "San Francisco"})
HomeCity.create!({name: "New York"})
HomeCity.create!({name: "Los Angeles"})
HomeCity.create!({name: "Boston"})

Gym.create!({name: "Crunch", home_city_id: 1})
Gym.create!({name: "LA Fitness", home_city_id: 1})
Gym.create!({name: "24 Hour", home_city_id: 1})
Gym.create!({name: "Golds Gym", home_city_id: 2})

Exercise.create!({name: "Sit Up"})
Exercise.create!({name: "Plank"})
Exercise.create!({name: "Bench"})
Exercise.create!({name: "Incline Bench"})
Exercise.create!({name: "Decline Bench"})
Exercise.create!({name: "Dumbbell Bench Press"})
Exercise.create!({name: "Chest Flies"})
Exercise.create!({name: "Cable Crossover"})
Exercise.create!({name: "Squat"})
Exercise.create!({name: "Leg Press"})
Exercise.create!({name: "Leg Curl"})
Exercise.create!({name: "Leg Extension"})
Exercise.create!({name: "Calf Raise"})
Exercise.create!({name: "Hip Extension"})
Exercise.create!({name: "Hip Abduction"})
Exercise.create!({name: "Deadlift"})
Exercise.create!({name: "Shoulder Press"})
Exercise.create!({name: "Arnold Dumbbell Press"})
Exercise.create!({name: "Back Fly"})
Exercise.create!({name: "Barbell Row"})
Exercise.create!({name: "Dumbbell Row"})
Exercise.create!({name: "Face Pull"})
Exercise.create!({name: "Lateral Raise"})
Exercise.create!({name: "Deltoid Raise"})
Exercise.create!({name: "Pullups"})
Exercise.create!({name: "Lat Pulldowns"})
Exercise.create!({name: ""})
Exercise.create!({name: " "})
Exercise.create!({name: " "})
Exercise.create!({name: " "})

time = Time.new
date = Date.current
Workout.create!({name: "Workout 1", user_id: 1, buddy_id: 2, date: date + 1, time: time + 30})
Workout.create!({name: "Workout 2", user_id: 2, buddy_id: 4, date: date + 2, time: time + 45})
Workout.create!({name: "Workout 3", user_id: 1, date: date + 3, time: time + 60})
Workout.create!({name: "Workout 4", user_id: 1, buddy_id: 2, date: date + 1, time: time + 30})
Workout.create!({name: "Workout 5", user_id: 2, buddy_id: 4, date: date + 2, time: time + 45})
Workout.create!({name: "Workout 6", user_id: 1, date: date + 3, time: time + 60})
Workout.create!({name: "Workout 7", user_id: 1, buddy_id: 2, date: date + 1, time: time + 30})
Workout.create!({name: "Workout 8", user_id: 2, buddy_id: 4, date: date + 2, time: time + 45})
Workout.create!({name: "Workout 9", user_id: 1, date: date + 3, time: time + 60})
Workout.create!({name: "Workout 10", user_id: 1, buddy_id: 2, date: date + 1, time: time + 30})
Workout.create!({name: "Workout 11", user_id: 2, buddy_id: 4, date: date + 2, time: time + 45})
Workout.create!({name: "Workout 12", user_id: 1, date: date + 3, time: time + 60})

WorkoutExercise.create!({workout_id: 1, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 1, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 1, exercise_id: 3, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 1, exercise_id: 4, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 1, exercise_id: 5, sets: 3, reps: 12})
WorkoutExercise.create!({workout_id: 2, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 2, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 2, exercise_id: 3, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 2, exercise_id: 4, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 3, exercise_id: 1, sets: 3, reps: 20})
WorkoutExercise.create!({workout_id: 3, exercise_id: 2, sets: 3, reps: 15})
WorkoutExercise.create!({workout_id: 3, exercise_id: 3, sets: 3, reps: 10})
WorkoutExercise.create!({workout_id: 4, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 4, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 4, exercise_id: 3, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 4, exercise_id: 4, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 5, exercise_id: 5, sets: 3, reps: 12})
WorkoutExercise.create!({workout_id: 5, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 5, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 5, exercise_id: 3, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 6, exercise_id: 4, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 6, exercise_id: 1, sets: 3, reps: 20})
WorkoutExercise.create!({workout_id: 6, exercise_id: 2, sets: 3, reps: 15})
WorkoutExercise.create!({workout_id: 6, exercise_id: 3, sets: 3, reps: 10})
WorkoutExercise.create!({workout_id: 7, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 7, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 7, exercise_id: 3, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 7, exercise_id: 4, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 8, exercise_id: 5, sets: 3, reps: 12})
WorkoutExercise.create!({workout_id: 8, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 8, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 8, exercise_id: 3, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 9, exercise_id: 4, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 9, exercise_id: 1, sets: 3, reps: 20})
WorkoutExercise.create!({workout_id: 9, exercise_id: 2, sets: 3, reps: 15})
WorkoutExercise.create!({workout_id: 9, exercise_id: 3, sets: 3, reps: 10})
WorkoutExercise.create!({workout_id: 10, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 10, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 10, exercise_id: 3, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 10, exercise_id: 4, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 11, exercise_id: 5, sets: 3, reps: 12})
WorkoutExercise.create!({workout_id: 11, exercise_id: 1, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 11, exercise_id: 2, sets: 5, reps: 5})
WorkoutExercise.create!({workout_id: 11, exercise_id: 3, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 12, exercise_id: 4, sets: 3, reps: 8})
WorkoutExercise.create!({workout_id: 12, exercise_id: 1, sets: 3, reps: 20})
WorkoutExercise.create!({workout_id: 12, exercise_id: 2, sets: 3, reps: 15})
WorkoutExercise.create!({workout_id: 12, exercise_id: 3, sets: 3, reps: 10})
